# Generated by Django 5.0.3 on 2025-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['time']},
        ),
    ]
