# Generated by Django 5.0.3 on 2025-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0002_user_alter_chat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='outer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
