# Generated by Django 5.0.3 on 2025-09-04 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0003_chat_outer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
