# Generated by Django 5.0.3 on 2025-09-04 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_user_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
