# Generated by Django 5.0.3 on 2025-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0005_alter_user_reg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
