# Generated by Django 5.0.3 on 2025-09-04 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0006_user_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 6, 24, 52, 868187, tzinfo=datetime.timezone.utc)),
        ),
    ]
