# Generated by Django 5.0.3 on 2025-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0007_alter_user_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
