# Generated by Django 5.0.3 on 2025-12-30 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0011_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
