# Generated by Django 5.0.3 on 2025-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0012_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
