# Generated by Django 5.0.3 on 2025-12-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0013_alter_audio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
