# Generated by Django 5.0.3 on 2025-12-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0014_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=400),
        ),
    ]
