# Generated by Django 5.0.3 on 2025-12-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0015_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
