# Generated by Django 5.0.3 on 2025-12-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0017_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
